[package]
name = "aoc24"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.2"
indoc = "2"
num-integer = "0.1.45"
itertools = "0.12.0"
priority-queue = "1.3.2"
rand = "0.8.5"
gomez = "0.5.0"